# Generated by Django 6.0.4 on 2026-04-12 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlamesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=120)),
                ('name2', models.CharField(max_length=120)),
                ('cleaned_name1', models.CharField(max_length=120)),
                ('cleaned_name2', models.CharField(max_length=120)),
                ('remaining_count', models.PositiveIntegerField()),
                ('relationship', models.CharField(choices=[('Friends', 'Friends'), ('Love', 'Love'), ('Affection', 'Affection'), ('Marriage', 'Marriage'), ('Enemies', 'Enemies'), ('Siblings', 'Siblings')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flames_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
